# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mastergui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MasterGUI(object):
    def setupUi(self, MasterGUI):
        MasterGUI.setObjectName("MasterGUI")
        MasterGUI.resize(784, 743)
        self.centralWidget = QtWidgets.QWidget(MasterGUI)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.overallTabs = QtWidgets.QTabWidget(self.centralWidget)
        self.overallTabs.setAutoFillBackground(True)
        self.overallTabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.overallTabs.setUsesScrollButtons(True)
        self.overallTabs.setMovable(True)
        self.overallTabs.setTabBarAutoHide(True)
        self.overallTabs.setObjectName("overallTabs")
        self.tab_User = QtWidgets.QWidget()
        self.tab_User.setObjectName("tab_User")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_User)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayoutGradingView = QtWidgets.QGridLayout()
        self.gridLayoutGradingView.setSpacing(6)
        self.gridLayoutGradingView.setObjectName("gridLayoutGradingView")
        self.showPathPushBotton = QtWidgets.QPushButton(self.tab_User)
        self.showPathPushBotton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showPathPushBotton.setFont(font)
        self.showPathPushBotton.setObjectName("showPathPushBotton")
        self.gridLayoutGradingView.addWidget(self.showPathPushBotton, 1, 0, 2, 2)
        self.specifyPath = QtWidgets.QPushButton(self.tab_User)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specifyPath.sizePolicy().hasHeightForWidth())
        self.specifyPath.setSizePolicy(sizePolicy)
        self.specifyPath.setMaximumSize(QtCore.QSize(150, 16777215))
        self.specifyPath.setAutoDefault(False)
        self.specifyPath.setDefault(False)
        self.specifyPath.setFlat(False)
        self.specifyPath.setObjectName("specifyPath")
        self.gridLayoutGradingView.addWidget(self.specifyPath, 0, 0, 1, 2)
        self.searchPushButton = QtWidgets.QPushButton(self.tab_User)
        self.searchPushButton.setObjectName("searchPushButton")
        self.gridLayoutGradingView.addWidget(self.searchPushButton, 1, 3, 2, 1)
        self.label_JavaViewer = QtWidgets.QLabel(self.tab_User)
        self.label_JavaViewer.setObjectName("label_JavaViewer")
        self.gridLayoutGradingView.addWidget(self.label_JavaViewer, 0, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.searchBoxLineEdit = QtWidgets.QLineEdit(self.tab_User)
        self.searchBoxLineEdit.setObjectName("searchBoxLineEdit")
        self.gridLayoutGradingView.addWidget(self.searchBoxLineEdit, 1, 2, 2, 1)
        self.javaViewer = QtWidgets.QTextEdit(self.tab_User)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.javaViewer.sizePolicy().hasHeightForWidth())
        self.javaViewer.setSizePolicy(sizePolicy)
        self.javaViewer.setObjectName("javaViewer")
        self.gridLayoutGradingView.addWidget(self.javaViewer, 3, 0, 1, 4)
        self.gridLayout_3.addLayout(self.gridLayoutGradingView, 0, 1, 1, 1)
        self.overallTabs.addTab(self.tab_User, "")
        self.tab_Business = QtWidgets.QWidget()
        self.tab_Business.setObjectName("tab_Business")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_Business)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.editableTableView = QtWidgets.QTableView(self.tab_Business)
        self.editableTableView.setObjectName("editableTableView")
        self.gridLayout_6.addWidget(self.editableTableView, 1, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.tab_Business)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_Business)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_6.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.overallTabs.addTab(self.tab_Business, "")
        self.gridLayout_2.addWidget(self.overallTabs, 0, 0, 1, 1)
        MasterGUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MasterGUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 784, 22))
        self.menuBar.setObjectName("menuBar")
        MasterGUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MasterGUI)
        self.mainToolBar.setObjectName("mainToolBar")
        MasterGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MasterGUI)
        self.statusBar.setObjectName("statusBar")
        MasterGUI.setStatusBar(self.statusBar)

        self.retranslateUi(MasterGUI)
        self.overallTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MasterGUI)

    def retranslateUi(self, MasterGUI):
        _translate = QtCore.QCoreApplication.translate
        MasterGUI.setWindowTitle(_translate("MasterGUI", "MasterGUI"))
        self.showPathPushBotton.setText(_translate("MasterGUI", "Connect"))
        self.specifyPath.setText(_translate("MasterGUI", "DB Server"))
        self.searchPushButton.setText(_translate("MasterGUI", "Search"))
        self.label_JavaViewer.setText(_translate("MasterGUI", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">User Search</span></p></body></html>"))
        self.overallTabs.setTabText(self.overallTabs.indexOf(self.tab_User), _translate("MasterGUI", "Grading"))
        self.pushButton.setText(_translate("MasterGUI", "Search"))
        self.overallTabs.setTabText(self.overallTabs.indexOf(self.tab_Business), _translate("MasterGUI", "Edit DB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MasterGUI = QtWidgets.QMainWindow()
    ui = Ui_MasterGUI()
    ui.setupUi(MasterGUI)
    MasterGUI.show()
    sys.exit(app.exec_())

